# from django.test import TestCase
import sqlite3
import pandas as pd


conn = sqlite3.connect('C:\\Users\\corpl\\OneDrive\\DA3_SYSTEMS\\dae_sys\\db.sqlite3')

cursor = conn.cursor()


# #ler dados
dados = ['BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'BAIXO', 'AMAZONAS', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'MARAJÓ', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'METROPOLITANA', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'NORDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE', 'SUDOESTE']

# df = pd.DataFrame(dados)

# print(df)

# # Inserindo os dados do DataFrame na tabela 'pessoas' (assumindo que ela já existe)
# df.to_sql('dae_web_sys_custos', conn, if_exists='append', index=False)

# # Listando todas as tabelas
# cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
# tables = cursor.fetchall()
# for table in tables:
#     print(table[0])

# cursor.execute('DELETE FROM dae_web_sys_regiao_municipio')

# conn.execute('''
#           CREATE TABLE IF NOT EXISTS minha_tabela (
#               id INTEGER PRIMARY KEY AUTOINCREMENT,
#               meso TEXT,
#               regiao TEXT,
#               municipio TEXT
#           )
#           ''')

for i in range(1, 145):
    valor = dados[i]  # Exemplo de valor para a nova coluna
    conn.execute(f"UPDATE dae_web_sys_regiao_municipio SET meso = '{valor}' WHERE id = {i}")

# Visualizando os dados de uma tabela específica
# cursor.execute("SELECT * FROM dae_web_sys_regiao_municipio")
# results = cursor.fetchall()
# for row in results:
#     print(row)

# # Comando para apagar a tabela "minha_tabela"
# cursor.execute("DROP TABLE IF EXISTS minha_tabela")

#salvando
conn.commit()

# Fechando a conexão
conn.close()

# var = '''

# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# BAIXO AMAZONAS
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# MARAJÓ
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# METROPOLITANA
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# NORDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE
# SUDOESTE


# '''

# print(var.split())