# Generated by Django 5.1.5 on 2025-01-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='regiao_municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(default='', max_length=40)),
                ('municipio', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
