# Generated by Django 5.1.5 on 2025-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dae_web_sys', '0002_custos'),
    ]

    operations = [
        migrations.CreateModel(
            name='reajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(default='', max_length=40)),
                ('indice', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Reajuste',
            },
        ),
        migrations.AlterModelOptions(
            name='custos',
            options={'verbose_name': 'Custos dos Serviço'},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'verbose_name': 'Regiõe'},
        ),
        migrations.AlterModelOptions(
            name='regiao_municipio',
            options={'verbose_name': 'Município'},
        ),
    ]
