# Generated by Django 5.1.5 on 2025-02-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dae_web_sys', '0003_reajuste_alter_custos_options_alter_regiao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesorregiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesorregiao', models.CharField(default='', max_length=40)),
            ],
            options={
                'verbose_name': 'Mesorregiõe',
            },
        ),
    ]
