# Generated by Django 5.1.5 on 2025-02-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dae_web_sys', '0004_mesorregiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiao_municipio',
            name='meso',
            field=models.CharField(default='', max_length=40),
        ),
    ]
